/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SdsDemoRouteImport } from './routes/sds-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContractsContractIdExplorerRouteImport } from './routes/contracts/$contractId/explorer'

const SdsDemoRoute = SdsDemoRouteImport.update({
  id: '/sds-demo',
  path: '/sds-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsContractIdExplorerRoute =
  ContractsContractIdExplorerRouteImport.update({
    id: '/contracts/$contractId/explorer',
    path: '/contracts/$contractId/explorer',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sds-demo': typeof SdsDemoRoute
  '/contracts/$contractId/explorer': typeof ContractsContractIdExplorerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sds-demo': typeof SdsDemoRoute
  '/contracts/$contractId/explorer': typeof ContractsContractIdExplorerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sds-demo': typeof SdsDemoRoute
  '/contracts/$contractId/explorer': typeof ContractsContractIdExplorerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sds-demo' | '/contracts/$contractId/explorer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sds-demo' | '/contracts/$contractId/explorer'
  id: '__root__' | '/' | '/sds-demo' | '/contracts/$contractId/explorer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SdsDemoRoute: typeof SdsDemoRoute
  ContractsContractIdExplorerRoute: typeof ContractsContractIdExplorerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sds-demo': {
      id: '/sds-demo'
      path: '/sds-demo'
      fullPath: '/sds-demo'
      preLoaderRoute: typeof SdsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$contractId/explorer': {
      id: '/contracts/$contractId/explorer'
      path: '/contracts/$contractId/explorer'
      fullPath: '/contracts/$contractId/explorer'
      preLoaderRoute: typeof ContractsContractIdExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SdsDemoRoute: SdsDemoRoute,
  ContractsContractIdExplorerRoute: ContractsContractIdExplorerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
